version: "3"

services:
  mongo:
    image: mongo:latest
    container_name: "mongo"
    volumes:
      - ./countainer_data/mongodir/:/data/db/:rw
    networks:
      - front
    ports:
      - "27018:27017"

  db:
    build: mysql/
    container_name: "db"
    environment:
      MYSQL_DATABASE: 'vkparser'
      MYSQL_USER: 'vkparser'
      MYSQL_PASSWORD: 'vkparser'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./countainer_data/mysqldir/:/var/lib/mysql/:rw
    networks:
      - front
    ports:
      - "3311:3306"

  web:
    build: web/
    container_name: "web"
    entrypoint: /code/docker-entrypoint.sh
    volumes:
      - ./web/code/:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      - mongo
    networks:
      - front

networks:
  front: